# new_book_type
Book.create(book_type: 'new_testament', name: 'Matthew', parts_number: 28)
Book.create(book_type: 'new_testament', name: 'Mark', parts_number: 16)
Book.create(book_type: 'new_testament', name: 'Luke', parts_number: 24)
Book.create(book_type: 'new_testament', name: 'John', parts_number: 21)
Book.create(book_type: 'new_testament', name: 'Acts', parts_number: 28)
Book.create(book_type: 'new_testament', name: 'Romans', parts_number: 16)
Book.create(book_type: 'new_testament', name: '1 Corinthians', parts_number: 16)
Book.create(book_type: 'new_testament', name: '2 Corinthians', parts_number: 13)
Book.create(book_type: 'new_testament', name: 'Galatians', parts_number: 6)
Book.create(book_type: 'new_testament', name: 'Ephesians', parts_number: 6)
Book.create(book_type: 'new_testament', name: 'Philippians', parts_number: 4)
Book.create(book_type: 'new_testament', name: 'Colossians', parts_number: 4)
Book.create(book_type: 'new_testament', name: '1 Thessalonians', parts_number: 5)
Book.create(book_type: 'new_testament', name: '2 Thessalonians', parts_number: 3)
Book.create(book_type: 'new_testament', name: '1 Timothy', parts_number: 6)
Book.create(book_type: 'new_testament', name: '2 Timothy', parts_number: 4)
Book.create(book_type: 'new_testament', name: 'Titus', parts_number: 3)
Book.create(book_type: 'new_testament', name: 'Philemon', parts_number: 1)
Book.create(book_type: 'new_testament', name: 'Hebrews', parts_number: 13)
Book.create(book_type: 'new_testament', name: 'James', parts_number: 5)
Book.create(book_type: 'new_testament', name: '1 Peter', parts_number: 5)
Book.create(book_type: 'new_testament', name: '2 Peter', parts_number: 3)
Book.create(book_type: 'new_testament', name: '1 John', parts_number: 5)
Book.create(book_type: 'new_testament', name: '2 John', parts_number: 1)
Book.create(book_type: 'new_testament', name: '3 John', parts_number: 1)
Book.create(book_type: 'new_testament', name: 'Jude', parts_number: 1)
Book.create(book_type: 'new_testament', name: 'Revelation', parts_number: 22)


# old_testament
Book.create(book_type: 'old_testament', name: 'Genesis', parts_number: 50)
Book.create(book_type: 'old_testament', name: 'Exodus', parts_number: 40)
Book.create(book_type: 'old_testament', name: 'Leviticus', parts_number: 27)
Book.create(book_type: 'old_testament', name: 'Numbers', parts_number: 36)
Book.create(book_type: 'old_testament', name: 'Deuteronomy', parts_number: 34)
Book.create(book_type: 'old_testament', name: 'Joshua', parts_number: 24)
Book.create(book_type: 'old_testament', name: 'Judges', parts_number: 21)
Book.create(book_type: 'old_testament', name: 'Ruth', parts_number: 4)
Book.create(book_type: 'old_testament', name: '1 Samuel', parts_number: 31)
Book.create(book_type: 'old_testament', name: '2 Samuel', parts_number: 24)
Book.create(book_type: 'old_testament', name: '1 Kings', parts_number: 22)
Book.create(book_type: 'old_testament', name: '2 Kings', parts_number: 25)
Book.create(book_type: 'old_testament', name: '1 Chronicles', parts_number: 29)
Book.create(book_type: 'old_testament', name: '2 Chronicles', parts_number: 36)
Book.create(book_type: 'old_testament', name: 'Ezra', parts_number: 10)
Book.create(book_type: 'old_testament', name: 'Nehemiah', parts_number: 13)
Book.create(book_type: 'old_testament', name: 'Esther', parts_number: 9)
Book.create(book_type: 'old_testament', name: 'Job', parts_number: 42)
Book.create(book_type: 'old_testament', name: 'Psalm', parts_number: 150)
Book.create(book_type: 'old_testament', name: 'Proverbs', parts_number: 31)
Book.create(book_type: 'old_testament', name: 'Ecclesiastes', parts_number: 10)
Book.create(book_type: 'old_testament', name: 'Song of Solomon', parts_number: 8)
Book.create(book_type: 'old_testament', name: 'Isaiah', parts_number: 66)
Book.create(book_type: 'old_testament', name: 'Jeremiah', parts_number: 52)
Book.create(book_type: 'old_testament', name: 'Lamentations', parts_number: 5)
Book.create(book_type: 'old_testament', name: 'Ezekiel', parts_number: 48)
Book.create(book_type: 'old_testament', name: 'Daniel', parts_number: 12)
Book.create(book_type: 'old_testament', name: 'Hosea', parts_number: 14)
Book.create(book_type: 'old_testament', name: 'Joel', parts_number: 3)
Book.create(book_type: 'old_testament', name: 'Amos', parts_number: 9)
Book.create(book_type: 'old_testament', name: 'Obadiah', parts_number: 1)
Book.create(book_type: 'old_testament', name: 'Jonah', parts_number: 4)
Book.create(book_type: 'old_testament', name: 'Micah', parts_number: 7)
Book.create(book_type: 'old_testament', name: 'Nahum', parts_number: 3)
Book.create(book_type: 'old_testament', name: 'Habakkuk', parts_number: 3)
Book.create(book_type: 'old_testament', name: 'Zephaniah', parts_number: 3)
Book.create(book_type: 'old_testament', name: 'Haggai', parts_number: 1)
Book.create(book_type: 'old_testament', name: 'Zechariah', parts_number: 14)
Book.create(book_type: 'old_testament', name: 'Malachi', parts_number: 4)
